name: flutter_gank
description: This is a Gank App both Android and Ios

version: 1.0.1

dependencies:

  flutter:
    sdk: flutter

  http:
    ^0.12.0


  pull_to_refresh:  1.5.0
  flutter_sticky_header: 0.4.0
  residemenu:
    1.3.6

  sqflite:
    ^1.1.6

  # android complie error
  #flutter_webview_plugin: 0.3.5

  webview_flutter: 0.3.10
  photo_view: 0.4.2
  flutter_swiper: ^1.1.6
  shared_preferences: ^0.5.3+2

  share: ^0.6.1+1

  flutter_staggered_grid_view: 0.3.0

  cached_network_image:
    ^1.1.0

  flutter_spinkit: ^3.1.0

  flutter_colorpicker: ^0.2.5



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/gank.jpg
    - images/empty.png
    - images/splash.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
